---
- name: Perform yum update, capture output, and reboot server
  hosts: all
  become: yes
  vars:
    result_file: /tmp/yum_update_last10.txt
    error_file: /tmp/error.txt

  tasks:
    - name: Run 'yum update -y' and capture output
      shell: |
        yum update -y > /tmp/yum_update_full.txt 2>&1
        tail -n 10 /tmp/yum_update_full.txt > {{ result_file }}
      register: yum_result
      ignore_errors: yes

    - name: Save error output if yum update failed
      copy:
        content: "{{ yum_result.stderr }}"
        dest: "{{ error_file }}"
      when: yum_result.failed

    - name: Reboot the server
      reboot:
        reboot_timeout: 600
      register: reboot_result
      ignore_errors: yes

    - name: Wait for server to become reachable after reboot
      wait_for_connection:
        timeout: 300
      register: wait_result
      ignore_errors: yes

    - name: Show result if server is online
      debug:
        msg: "wait until server is online"
      when: wait_result is succeeded

    - name: Show error if server is not online
      shell: cat {{ error_file }}
      register: error_output
      when: wait_result is failed

    - name: Output error message if server is not online
      debug:
        msg: "{{ error_output.stdout }}"
      when: wait_result is failed
